server:
  port: 5666
spring:
  application:
    name: soa
  jersey:
    application-path: /api
  datasource:
    url: jdbc:postgresql://localhost:5432/studs
    username: s291485
    password: qz6XMfGNKAgNOWkq
  jpa:
    datasource: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
